name: NASA  Project CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    env: 
      COOKIE_KEY_1: ${{ secrets.COOKIE_KEY_1 }}      
      COOKIE_KEY_2: ${{ secrets.COOKIE_KEY_2 }}           
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}      
      OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}      
      PORT: ${{ secrets.PORT }}  
      CI: true 
      MONGO_URL: mongodb://localhost/nasa-project
    strategy:
        matrix:
          node-version: [20.x]
          mongodb-version: ['7.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - run: npm install
      - run: npm run build --prefix client 
      - run: npm test
        